### ISSUE TITLE
Usage Instructions? 

### ISSUE THREAD

**Issue by alburse** [airis4d/CASSPER#16]
Is there any instructions for how to use CASSPER? I only see installation instructions.

Thank you,

Alpay

**Comment by sajeethphilip** [comment]
Please find Instructions for using CASSPER  in the README file of
https://github.com/airis4d/CASSPER. Detailed instruction for labelling,
training and prediction are given in respective subfolders

_________________________________________________________________

Ninan Sajeeth Philip PhD
(From mobile)

Visiting Professor [IUCAA, Pune],

Adjunct Professor of AI in Applied Medical Sciences [BCMCH, Thiruvalla],

Dean and Director,
Artificial Intelligence Research and Intelligent Systems

Thelliyoor -689544

Kerala, INDIA

Phone: +91-9497552476, 9496552479, 8149134586
                                 e-mail: ***@***.***


Research Interests :Artificial Intelligence, Cryptography, Biodiversity
home page          : www.iucaa.in/~nspp

Citations: https://scholar.google.co.in/citations?user=VRP34wsAAAAJ&hl=en

Don't be shy to share ideas. You will never exhaust them, but will rather
multiply. - personal view

**Comment by alburse** [comment]
Hi Ninan Sajeeth
Great, I would suggest mentioning detailed instruction being in the subfolders.

Thank you.

**Comment by sajeethphilip** [comment]
Thank you for your suggestion. Will do that.
_________________________________________________________________

Ninan Sajeeth Philip PhD
(From mobile)

Visiting Professor [IUCAA, Pune],

Adjunct Professor of AI in Applied Medical Sciences [BCMCH, Thiruvalla],

Dean and Director,
Artificial Intelligence Research and Intelligent Systems

Thelliyoor -689544

Kerala, INDIA

Phone: +91-9497552476, 9496552479, 8149134586
                                 e-mail: ***@***.***


Research Interests :Artificial Intelligence, Cryptography, Biodiversity
home page          : www.iucaa.in/~nspp

Citations: https://scholar.google.co.in/citations?user=VRP34wsAAAAJ&hl=en

Don't be shy to share ideas. You will never exhaust them, but will rather
multiply. - personal view
